package easy;

import com.sun.javafx.binding.ContentBinding;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e


 Explanation:
 'e' is the letter that was added.
 * @author NikoBelic
 * @create 16/9/3 15:13
 */
public class FindTheDifference
{
    public char findTheDifference(String s, String t)
    {
        for (int i = 0 ; i < s.length() ; i ++)
        {
            char c = s.charAt(i);
            int tIndex = t.indexOf(c);
            t = t.replaceFirst(String.valueOf(c), "");
        }
        for (int j = 0 ; j < t.length(); j++)
        {
            if (String.valueOf(t.charAt(j)) != "")
            {
                return t.charAt(j);
            }
        }
        return 'c';
    }
    public static void main(String[] args)
    {
        FindTheDifference f = new FindTheDifference();
        System.out.println(f.findTheDifference("HelloWorlds","WordsKHello"));
    }
}
